### PR TITLE
remove exclusion of TS 2 options, add lib support

### LINKED ISSUE #315: TypeDoc doesn't support the lib option
I use the new `lib` option in `tsconfig.json` to explicitly set the [built-in type definitions](http://www.typescriptlang.org/docs/release-notes/typescript-2.0.html#including-built-in-type-declarations-with---lib) I want to use in my project:

``` json
{
    "$schema": "http://json.schemastore.org/tsconfig",
    "compilerOptions": {
        "target": "es5",
        "lib": [ "es2015.promise", "es2015.core", "es2015.collection", "es5", "dom" ],
        "module": "commonjs",
        "rootDir": "src",
        "outDir": "lib",
        "noEmitOnError": true,
        "sourceMap": true,
        "declaration": true,
    },
    "exclude": [
        "node_modules",
        "lib"
    ]
}
```

Unfortunately typedoc doesn't support this:

``` bash
$ typedoc --out doc src
Error: Unknown option `lib.0`.
Error: Unknown option `lib.1`.
Error: Unknown option `lib.2`.
Error: Unknown option `lib.3`.
Error: Unknown option `lib.4`.
```

For now I reverted back to using external type definitions for the needed ES2015 features so I'm able to use TypeDoc but it would be nice if TypeDoc could support this useful new feature.

### PR DESCRIPTION
**Pull request by nicknisi**
* Remove restriction on what compilerOptions can be set
* remove filtering of TS 2.2 compilerOptions
* add support for 'list' option types
* Switch to processed compilerOptions
* add support for `compilerOptions.lib`

This PR removes the restrictions on setting options that aren't explicitly setup as options to allow new compilerOptions to pass through TypeDoc to TypeScript. It also sets up support for 'list' parameter types, and switches to use the processed compilerOptions, rather than `raw` so that the `lib` properties are properly parsed.

This should fix #315 and I believe #311.

### CODE REVIEW

File: src/lib/utils/options/declaration.ts [hunk 1]
```diff
@@ -95,12 +95,13 @@ export class OptionDeclaration {
...
                 if (map !== 'object') {
                     const key = value ? (value + '').toLowerCase() : '';
+                    const values = Object.keys(map).map(key => map[key]);
 
                     if (map instanceof Map && map.has(key)) {
                         value = map.get(key);
                     } else if (key in map) {
                         value = map[key];
-                    } else if (errorCallback) {
+                    } else if (!~values.indexOf(value) && errorCallback) {
```
Comment (blakeembrey) [inline src/lib/utils/options/declaration.ts]: Can we use the non-clever format of `indexOf`, cheers! 😄

Comment (nicknisi) [inline src/lib/utils/options/declaration.ts]: Removed! Sorry about that!

File: src/lib/utils/options/options.ts [hunk 2]
```diff
@@ -152,10 +152,10 @@ export class Options extends ChildableComponent<Application, OptionsComponent> {
             const value = obj[key];
             const declaration = this.getDeclaration(key);
             const shouldValueBeAnObject = declaration && declaration['map'] === 'object';
-            if (typeof value === 'object' && !shouldValueBeAnObject) {
+            if (!Array.isArray(value) && typeof value === 'object' && !shouldValueBeAnObject) {
                 this.setValues(value, prefix + key + '.', errorCallback);
             } else {
-                this.setValue(prefix + key, value, errorCallback);
+                this.setValue(prefix + key, value);
```
Comment (blakeembrey) [inline src/lib/utils/options/options.ts]: Was there a reason behind this signature change?

File: src/lib/utils/options/readers/tsconfig.ts [hunk 3]
```diff
@@ -51,31 +51,30 @@ export class TSConfigReader extends OptionsComponent {
             return;
         }
 
-        let data = ts.readConfigFile(fileName, ts.sys.readFile).config;
-        if (data === undefined) {
+        let { config } = ts.readConfigFile(fileName, ts.sys.readFile);
```
Comment (blakeembrey) [inline src/lib/utils/options/readers/tsconfig.ts]: Could we use `const` if there's no other mutation?

**Comment by blakeembrey** [comment]
Sorry for the delay, I just had a couple of last comments. Once those are reviewed, I'm happy to merge!

**Comment by nicknisi** [comment]
@blakeembrey Thanks! I rebased off the latest master and pushed up two commits to address your comments. Regarding the signature change, I actually modified my approach now that `OptionDeclaration#map` is a `Map`. The big thing I changed with this code (and the previous signature change) was that I am trying to let unknown-to-TypeDoc options simply pass through without throwing an error. That way, TypeDoc doesn't need to maintain a whitelist of `compilerOptions`, and should be more future proof.

Also, I checked in a number of changes to the built files (in a separate commit). These changes aren't related to this work, and appear when running the tests, even on master. I can remove this commit if you like.

**Comment by blakeembrey** [comment]
Thanks @nicknisi! ❤️ 

I'm going to make a minor edit since it looks like you accidentally inserted a tab where there's spaces, then I'll merge 👍

**Comment by blakeembrey** [comment]
Weird. I just pulled this in and tested, but I end up reverting all the `.html` changes you recently made. Do you have something locally affecting that?

**Comment by nicknisi** [comment]
Yep, you're totally right... I didn't realize I had the themes repo `npm link`'d in!
